//
// Created by wridz on 15/11/2021.
//

#ifndef ASSIGNMENT_1___BANKREKENING_TRANACTIONHISTORY_H
#define ASSIGNMENT_1___BANKREKENING_TRANACTIONHISTORY_H


class TranactionHistory {

};


#endif //ASSIGNMENT_1___BANKREKENING_TRANACTIONHISTORY_H
